# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# Uncomment and fill in once GitHub Sponsors / etc. are configured.
#
# github: [your-handle]
# custom: ['https://smirks.dev/sponsor']
