/**
 * Regenerates test/__fixtures__/golden.json — the pinned output that makes the
 * determinism guarantee falsifiable. It records:
 *   - fnv1a(seed) for every fixture seed (pins the hash itself)
 *   - bitmapToPath(variant) for every eye and mouth (pins the data and the RLE)
 *   - the complete SVG string for every seed x mode combination
 *
 * Layered so a failure localises: a changed hash fails one block, a redrawn
 * variant another, a palette edit only the third.
 *
 * MAINTAINER-ONLY and DELIBERATE. The fixture is a tripwire — regenerating it
 * is how you accept that every existing avatar just changed, so only run this
 * when that is the intent, then read the diff before committing it.
 *
 * See CLAUDE.md "Determinism".
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { EYES } from '../src/data/eyes';
import { MOUTHS } from '../src/data/mouths';
import { fnv1a } from '../src/hash';
import { palettes } from '../src/palettes';
import { bitmapToPath, generateSvg, type SvgOptions } from '../src/render';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const FIXTURE_DIR = join(REPO_ROOT, 'test', '__fixtures__');

type PaletteName = keyof typeof palettes;

type GoldenOptions = {
  palette?: PaletteName;
  mode?: 'currentColor';
  fg?: string;
  bg?: string;
  title?: string;
};

type GoldenCase = { seed: string | number; options: GoldenOptions };

// ---------- Fixture inputs ----------

/**
 * Chosen greedily over s0, s1, s2, ... until every eye (12), every mouth (8) and
 * every colour pair (13) had been hit at least once.
 * Hardcoded rather than recomputed so the fixture diffs stay small: when a
 * variant changes, the seeds stay put and only the values move.
 */
const COVERING_SEEDS = [
  's0',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6',
  's7',
  's8',
  's9',
  's10',
  's11',
  's12',
  's13',
  's14',
  's15',
  's16',
  's19',
  's24',
  's28',
  's33',
];

/** Inputs that exercise the seed contract rather than the variant space. */
const EDGE_SEEDS: (string | number)[] = [
  '',
  '42',
  42,
  'a',
  '🦊',
  // Same word, two normalisations, two different strings — and so two different
  // avatars. Pinned to document that the seed is hashed as given, never folded.
  'café'.normalize('NFC'),
  'café'.normalize('NFD'),
  'a-seed-long-enough-to-run-the-hash-loop-a-few-hundred-times'.repeat(4),
];

/** A small fixed subset carries the non-default modes; more would be noise. */
const MODE_SEEDS = ['s0', 's1', 's2'];

const MODE_OPTIONS: GoldenOptions[] = [
  { palette: 'bold' },
  { palette: 'monochromeLight' },
  { palette: 'monochromeDark' },
  { palette: 'duotone' },
  { mode: 'currentColor' },
  { fg: '#ffffff' },
  { bg: '#000000' },
  { fg: '#ffffff', bg: '#000000' },
];

/** Escaping and XML-legality cases, pinned so a regression is visible. */
const TITLE_CASES: GoldenCase[] = [
  { seed: 's0', options: { title: 'Alice Liddell' } },
  { seed: 's0', options: { title: '<Alice> & "Bob"' } },
  { seed: 's0', options: { title: "O'Brien" } },
  { seed: 's0', options: { title: `Bob${String.fromCharCode(0x0b)}Smith` } },
  { seed: 's0', options: { title: `a${String.fromCharCode(0xd800)}b` } },
  { seed: 's0', options: { title: 'tab\tnewline\nreturn\r' } },
  { seed: 's0', options: { title: '中文 emoji 🦊' } },
];

// ---------- Assembly ----------

function toSvgOptions(options: GoldenOptions): SvgOptions {
  const { palette, mode, fg, bg, title } = options;
  if (mode === 'currentColor') {
    return { mode, title };
  }
  return { palette: palette === undefined ? undefined : palettes[palette], fg, bg, title };
}

function buildCases(): GoldenCase[] {
  const cases: GoldenCase[] = [];
  for (const seed of [...COVERING_SEEDS, ...EDGE_SEEDS]) {
    cases.push({ seed, options: {} });
  }
  for (const seed of MODE_SEEDS) {
    for (const options of MODE_OPTIONS) {
      cases.push({ seed, options });
    }
  }
  cases.push(...TITLE_CASES);
  return cases;
}

function main(): void {
  const cases = buildCases();

  const fixture = {
    note: 'Generated by scripts/build-golden.ts — do not hand-edit. See CLAUDE.md "Determinism".',
    // `fnv1a` is string -> number, so the hash block pins normalised seeds.
    // `42` and '42' collapse to one entry here; the seed contract that makes
    // them equivalent is asserted in test/determinism.test.ts instead.
    hash: [...new Set([...COVERING_SEEDS, ...EDGE_SEEDS].map(String))].map((seed) => ({
      seed,
      value: fnv1a(seed),
    })),
    paths: {
      eyes: EYES.map((bitmap) => bitmapToPath(bitmap)),
      mouths: MOUTHS.map((bitmap) => bitmapToPath(bitmap)),
    },
    svg: cases.map(({ seed, options }) => ({
      seed,
      options,
      svg: generateSvg(seed, toSvgOptions(options)),
    })),
  };

  mkdirSync(FIXTURE_DIR, { recursive: true });
  const fixturePath = join(FIXTURE_DIR, 'golden.json');
  writeFileSync(fixturePath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');

  console.log(`  ✓ wrote ${fixture.hash.length} hashes -> test/__fixtures__/golden.json`);
  console.log(
    `  ✓ wrote ${fixture.paths.eyes.length} eye and ${fixture.paths.mouths.length} mouth paths`,
  );
  console.log(`  ✓ wrote ${fixture.svg.length} pinned SVGs`);
}

main();
